 const dsaTopics = [
    "All",
    "Arrays",
    "Strings",
    "Linked List",
    "Stacks",
    "Queues",
    "Hashing",
    "Recursion",
    "Backtracking",
    "Binary Search",
    "Two Pointers",
    "Sliding Window",
    "Greedy Algorithms",
    "Divide and Conquer",
    "Dynamic Programming",
    "Bit Manipulation",
    "Trees",
    "Binary Trees",
    "Binary Search Trees",
    "Trie",
    "Graphs",
    "Depth-First Search (DFS)",
    "Breadth-First Search (BFS)",
    "Topological Sort",
    "Shortest Path Algorithms",
    "Minimum Spanning Tree",
    "Union-Find / Disjoint Set",
    "Segment Tree",
    "Heap / Priority Queue",
    "Sorting Algorithms",
    "Mathematics for DSA ",
    "Number Theory",
    "Game Theory",
    "String Matching Algorithms",
    "Rolling Hash",
    "Geometry Algorithms",
    "Bitmasking"
  ];
  export default dsaTopics;