const dsaProblems = [
    { title: "Two Sum", level: "L1" },
    { title: "Reverse a Linked List", level: "L2" },
    { title: "Merge Two Sorted Lists", level: "L2" },
    { title: "Valid Parentheses", level: "L1" },
    { title: "Detect Cycle in a Linked List", level: "L3" },
    { title: "Find Minimum in Rotated Sorted Array", level: "L4" },
    { title: "Longest Substring Without Repeating Characters", level: "L4" },
    { title: "Maximum Subarray (Kadane's Algorithm)", level: "L2" },
    { title: "Climbing Stairs (DP)", level: "L2" },
    { title: "Coin Change", level: "L5" },
    { title: "Sort Colors (Dutch National Flag)", level: "L3" },
    { title: "Search in Binary Search Tree", level: "L2" },
    { title: "Lowest Common Ancestor of a BST", level: "L4" },
    { title: "Binary Tree Level Order Traversal", level: "L3" },
    { title: "Kth Smallest Element in BST", level: "L5" },
    { title: "Top K Frequent Elements", level: "L5" },
    { title: "Longest Palindromic Substring", level: "L5" },
    { title: "Find All Anagrams in a String", level: "L4" },
    { title: "Word Break (DP)", level: "L6" },
    { title: "House Robber", level: "L3" },
    { title: "Decode Ways", level: "L5" },
    { title: "Edit Distance", level: "L8" },
    { title: "Jump Game", level: "L4" },
    { title: "Partition Equal Subset Sum", level: "L5" },
    { title: "Course Schedule (Topological Sort)", level: "L6" },
    { title: "Number of Islands (DFS/BFS)", level: "L4" },
    { title: "Clone Graph", level: "L6" },
    { title: "Dijkstra's Algorithm", level: "L8" },
    { title: "Bellman-Ford Algorithm", level: "L9" },
    { title: "Minimum Spanning Tree (Kruskal's / Prim's)", level: "L7" },
    { title: "Union Find - Number of Connected Components", level: "L6" },
    { title: "LRU Cache", level: "L7" },
    { title: "Sliding Window Maximum", level: "L7" },
    { title: "Median of Two Sorted Arrays", level: "L10" }
  ];
  
  export default dsaProblems;
  